language: php
php:
- 7.1
- 7.2
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
  global:
  - secure: Cnp4YyQUMYDeAMb79PTzvzHiZRCxzcO1iLVf1tjOUnd57JGlpvF4WTb3JA+eUkTnpNXQJnGy1kzEYMaPiJl/Z30gyq3CeES+LIoLnhORH4KLmJCS9OejmFQq+l+/AgHj8zw6oJB8ui/gJxQ/lAiSyDPDyDp7ZJ/vAvwOtrECqW2zl88iXIb/tByn2W+OFX6BsG+ezlPDu8ULSy7YB6eSYlKSDdUM7hBH/vVqPpKewp0ElsU7c9G+jNYlaqjddlOsraYq1pnk/QAfTv4gSBxyxtqIdSg4xZKjJl4Pomg9goCR6r9uFYsfhJD5ahgcBXfCgdB4ozW27b2TlbbJSHWQ4YseU8kZxeUzH8PfQZzi4c7kuEezGdkP8P30NqFcV5agSp9Jsj7oesdZt08KZ5+ixUP0RzLoSm94jk35PQRNnzhcf/RqQBzH4CMJlqbctJJg8Prpa31y3MfoCV+TDTGXCXYtVgRwk2sXVcwYS37EqPj/YeqgketJZQnn/714Aeq6R0X1GaLkzHaHOT9PY8kHfiZZDsuFUs/e5GUfAMFmro5m4EfS0/rOAiGqM1uYzcfp5+rqepOtp/D8QnggTZ6RgxQynUIxPGowtcJI/Nb9ObeQBpxsgulehX0WWeO9xFQeyJatk/c/bY9B4jzQrPnv5S2ttysW6RpKVZZ1uDYJGX8=
  - secure: nuMoBfYYqdfvNGD5xzRkZWC0igDDf+boO/twH1N19IlsqA6SrG2MAHQK9Z+wHVvjtWB9aZ5KNJhWYS/SUyr7ByB5Yfkjr/jGFGtTAM+RCyCx/0UcY/7DzVfDDePG9iW4p7yKUWUfrDVdEWIznJzF72SgNa2THGtbiOEktD4ovOYAQuedd1Y0K4yA5tA3HeK/N0my1Kt39V0s6kjBuEC4LhogJnHFSiktJvBmN191ubG5JTW0t60vKun/gp8ep+Sis9cC6XyeXySGveYU8Ubd5xDj606yTVJTJg+89Y2L49QJsbSPjyn+x86/BRKI4tmONCLRNgxPVCoAk0TGwoxH0Djy+NZ2SCi5d9FtD/a2JjqVAvraXJctn5Wb0gNEvBXvzwYJLRsMNhgl0yyjly+MiQJiVrgtJG+iotKHQVOLBFiCRpn1J6UATpkeoCNOiIvsLhOCMmNy5MEOJ6JSqHQoyevUqZFIEAW2eZjPapBmEK2QYtSgCngy/g+BSwlsK5jtXp8uh1Zeeo8YBooKTSx6whFvJtWq6JOM3IJHnmfWiprkImN29lW81MikseeFA3ixGvr4ZxPsInOktslwTXYSs6xVdPWuwxMOhypChr+zE9o3VTvXEel5YEb0x+QXtDHV4gFik1gnFlFIymCy9txcxHEZG+9ZcKJg2HkY+dEGdAo=
install:
- echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}"
  > auth.json
before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
